apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:latest
          ports:
            - containerPort: 24224
              protocol: TCP
            - containerPort: 24224
              protocol: UDP
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/log
              subPath: log
      volumes:
        - name: fluentd-config
          hostPath:
            path: /path/to/dir
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
spec:
  ports:
    - port: 24224
      targetPort: 24224
      protocol: TCP
    - port: 24224
      targetPort: 24224
      protocol: UDP
  selector:
    app: fluentd
