apiVersion: v1
kind: Service
metadata:
  name: app-node
  labels:
    app: app-node
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: app-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
  labels:
    app: app-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
    spec:
      containers:
        - name: app-node
          image: frankawesome/app_node:latest
          ports:
            - containerPort: 8081
          env:
            - name: RABBITIP
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
