apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    name: http
  - port: 50000
    targetPort: 50000
    nodePort: 30002
    name: agent
  selector:
    app: jenkins
