apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  namespace: default  # Change if using a different namespace
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=dir:///workspace/"
    - "--destination=$(DESTINATION)"
    - "--cache=true"
    env:
    - name: DESTINATION
      value: "gcr.io/your-project/your-image:${IMAGE_TAG}"  # Example destination
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  restartPolicy: Never
  volumes:
  - name: workspace
    emptyDir: {}
