apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    app: webui
spec:
  ports:
    - port: 3000
      targetPort: 80
  selector:
    app: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: frankawesome/simple-angular-app:latest
          ports:
            - containerPort: 3000
