apiVersion: v1
kind: Service
metadata:
  name: app-rest
  labels:
    app: app-rest
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rest
  labels:
    app: app-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-rest
  template:
    metadata:
      labels:
        app: app-rest
    spec:
      containers:
        - name: app-rest
          image: frankawesome/rest-llm-5:latest
          ports:
            - containerPort: 5000
          env:
            - name: RABBITIP
              value: "rabbitmq"
            - name: REDIS_HOST
              value: "redis"
            - name: FLUENTD_HOST
              value: "fluentd"